app1/urls.py
from django.urls import path
from app1.views import *
app_name="manasa"

urlpatterns=[
    path('one',one,name='one'),
]

app2/urls.py
from django.urls import path
from app2.views import *
app_name='reddy'

urlpatterns=[
    path('two/',two,name='two'),
]

project14/urls.py
from django.contrib import admin
from django.urls import path,include
import app1,app2

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app1',include('app1.urls')),
    path('app2/',include('app2.urls')),

]

app1/models.py
from django.db import models

# Create your models here.

app2/models.py
from django.db import models

# Create your models here.

app1/views.py
from django.shortcuts import render

# Create your views here.
def one(request):
    return render(request,'one.html')

app2/views.py
from django.shortcuts import render

# Create your views here.
def two(request):
    return render(request,'two.html')

templates/one.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>my first page</h1>
        <h1><a href="{% url 'reddy:two' %}">second page</a></h1>
    </center>
    
</body>
</html>

templates/two.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>my second page</h1>
        <h1><a href="{% url 'manasa:one' %}">my first page</a></h1>
    </center>
</body>
</html>